{{- if and .Values.metadataService.enabled .Values.metadataService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "beema.fullname" . }}-metadata
  labels:
    app.kubernetes.io/name: {{ include "beema.name" . }}-metadata
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: metadata-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "beema.fullname" . }}-metadata
  minReplicas: {{ .Values.metadataService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.metadataService.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.metadataService.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.metadataService.autoscaling.targetMemoryUtilizationPercentage | default 80 }}
{{- end }}
