{{- if and .Values.metadataService.enabled .Values.observability.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "beema.fullname" . }}-metadata
  labels:
    app.kubernetes.io/name: {{ include "beema.name" . }}-metadata
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: metadata-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "beema.name" . }}-metadata
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
      scrapeTimeout: 10s
{{- end }}
