-- =============================================================================
-- V9: Human-in-the-Loop Task Inbox
-- =============================================================================
-- Creates the sys_tasks table which acts as the "Inbox" for human tasks
-- generated by Temporal workflows that require user approval/action.
-- The bridge pattern: Workflow creates task → User completes task → Signal resumes workflow.

CREATE TABLE sys_tasks (
    id              UUID            NOT NULL DEFAULT gen_random_uuid(),
    workflow_id     VARCHAR(500)    NOT NULL,
    run_id          VARCHAR(500)    NOT NULL,
    signal_name     VARCHAR(200)    NOT NULL DEFAULT 'HumanApproval',
    task_type       VARCHAR(100)    NOT NULL DEFAULT 'APPROVAL',
    title           VARCHAR(500)    NOT NULL,
    description     TEXT,
    assignee_role   VARCHAR(100)    NOT NULL,
    assignee_user   VARCHAR(200),
    status          VARCHAR(20)     NOT NULL DEFAULT 'OPEN',
    outcome         VARCHAR(100),
    outcome_data    JSONB           NOT NULL DEFAULT '{}'::jsonb,
    due_at          TIMESTAMPTZ,
    completed_at    TIMESTAMPTZ,
    completed_by    VARCHAR(200),
    tenant_id       VARCHAR(100)    NOT NULL DEFAULT 'default',
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CHECK (status IN ('OPEN', 'COMPLETED', 'CANCELLED', 'EXPIRED')),
    CHECK (task_type IN ('APPROVAL', 'REVIEW', 'ACTION', 'ESCALATION'))
);

-- Indexes
CREATE INDEX idx_sys_tasks_workflow      ON sys_tasks (workflow_id, run_id);
CREATE INDEX idx_sys_tasks_assignee      ON sys_tasks (assignee_role, status);
CREATE INDEX idx_sys_tasks_status        ON sys_tasks (status, tenant_id);
CREATE INDEX idx_sys_tasks_tenant        ON sys_tasks (tenant_id, created_at DESC);
CREATE INDEX idx_sys_tasks_due           ON sys_tasks (due_at) WHERE status = 'OPEN';

-- Auto-update updated_at
CREATE TRIGGER audit_sys_tasks
    BEFORE UPDATE ON sys_tasks
    FOR EACH ROW
    EXECUTE FUNCTION audit_trigger();

COMMENT ON TABLE sys_tasks IS 'Human-in-the-loop task inbox for Temporal workflow approvals';
COMMENT ON COLUMN sys_tasks.workflow_id IS 'Temporal workflow execution ID to signal on completion';
COMMENT ON COLUMN sys_tasks.run_id IS 'Temporal workflow run ID for the specific execution';
COMMENT ON COLUMN sys_tasks.signal_name IS 'Temporal signal name to send when task is completed';
COMMENT ON COLUMN sys_tasks.outcome IS 'Result of the human action: APPROVED, REJECTED, ESCALATED, etc.';
COMMENT ON COLUMN sys_tasks.outcome_data IS 'Additional structured data from the human decision';
