{{- if and .Values.studio.enabled .Values.studio.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "beema.fullname" . }}-studio
  labels:
    app.kubernetes.io/name: {{ include "beema.name" . }}-studio
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: studio
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "beema.fullname" . }}-studio
  minReplicas: {{ .Values.studio.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.studio.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.studio.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
