apiVersion: v1
kind: Secret
metadata:
  name: {{ include "beema.fullname" . }}
  labels:
    app: {{ include "beema.name" . }}
    chart: {{ include "beema.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  # Add your secret key-value pairs here (base64 encoded)
  # example-key: dmFsdWU=
