{{- if .Values.temporal.enabled }}
{{- if .Values.temporal.worker.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-temporal-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-temporal-worker
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    component: temporal-worker
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 8081
      targetPort: management
      protocol: TCP
      name: management
  selector:
    app: {{ .Chart.Name }}-temporal-worker
    release: {{ .Release.Name }}
{{- end }}
{{- end }}
